name: Sincronizar con Hugging Face
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Instalar Git Xet
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/huggingface/xet-core/refs/heads/main/git_xet/install.sh | sh
          git xet install

      - name: Configurar remoto de Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote remove space || true
          git remote add space https://Espartan00:${HF_TOKEN}@huggingface.co/spaces/Espartan00/Biomas-Proyect
          git remote -v

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git push --force space main
